### ISSUE TITLE
Replace the use of cmp()

### ISSUE THREAD

**Issue by astroDimitrios** [astroDimitrios/rose#1]
`cmp()` is deprecated and needs replacing.

`filecmp` seems to be fine as it is a Python 3 package.

[Function details](https://www.geeksforgeeks.org/python-cmp-function/)

**Comment by J-J-Abram** [comment]
cmp stands for compare?

Primary files of concern:

metomi -> rose -> config_editor & gtk

possible replacement: return (a > b) - (a < b)

**Comment by astroDimitrios** [comment]
```python
from functools import cmp_to_key
key=cmp_to_key()
```
the key can go inside `sort()`
