### ISSUE TITLE
List widget breaks formatting if the underlying Python syntax is broken

### ISSUE THREAD

**Issue by astroDimitrios** [astroDimitrios/rose#10]

**Comment by jfrost-mo** [comment]
This especially seems to happen when adding things that break the underlying python list syntax, such as adding quotes to insert a string. See this video for a demonstration:

https://github.com/user-attachments/assets/a2a4fce1-14b4-4cee-aae0-eb552617406d

**Comment by astroDimitrios** [comment]
Thanks @jfrost-mo I think this is slightly different than the bug mentioned in the title but I can confirm it also occurs with Rose 2019:
![image](https://github.com/user-attachments/assets/17c097fa-c861-460d-91c6-b0db9fadc660)
![image](https://github.com/user-attachments/assets/566ba18c-a59e-44b0-94e7-0a23e60b6b55)

We will look at it when we get a chance.

**Comment by jfrost-mo** [comment]
The widget formatting breaking is an issue that occurs in rose 2019 (https://github.com/metomi/rose/issues/2812). What is new in the python 3 port is that it also moves the focus from the text box to the menu cog. This prevents you being able to continue typing without clicking back in the text box.

**Comment by astroDimitrios** [comment]
This is now fixed unless you try and put a `"` mark inside another `"` mark. Still an improvement on old rose.
