### ISSUE TITLE
Replace .popup() calls

### ISSUE THREAD

**Issue by astroDimitrios** [astroDimitrios/rose#14]
Replace these deprecated calls with [popup_at_pointer](https://docs.gtk.org/gtk3/method.Menu.popup_at_pointer.html) or the other varients on these new popup functions instead of trying to fix them.

**Comment by J-J-Abram** [comment]
Requires replacing with gtk_menu_popup_at_pointer() or gtk_menu_popup_at_widget () 

Unclear which some need - changing to _widget by default unless it causes an issue

**Comment by astroDimitrios** [comment]
Closed by #20
