### ISSUE TITLE
Gtk warning attempt to allocate widget with negative heights

### ISSUE THREAD

**Issue by astroDimitrios** [astroDimitrios/rose#17]
Example:

![image](https://github.com/user-attachments/assets/9ce11520-bd3e-491e-bfc7-9006f0bfa9bc)

**Comment by J-J-Abram** [comment]
In metomi/rose/config_editor/page.py

line 115-116:
Commenting out this line removes the error prompt

Fixed by changing `set_border_width` with `set_margin_start` for left border and `set_margin_end` for right border and not including the top and bottom border equivalents
