### ISSUE TITLE
Remove PyGtk references

### ISSUE THREAD

**Issue by astroDimitrios** [astroDimitrios/rose#21]
For clarity we should remove any references to pygtk and check code that says PyGtk 2.18 etc for updates to later PyGtk versions.

**Comment by jfrost-mo** [comment]
Are you still using PyGtk?

To get it running I had to install PyGObject instead.

**Comment by astroDimitrios** [comment]
@jfrost-mo The new code is all PyGObject / Gtk3 :) 

There are still some references in code comments to PyGtk and one part of the codebase that says something along the lines of fix for pygtk ... which we should probably look at!
