### ISSUE TITLE
Extension: metadata graph

### ISSUE THREAD

**Issue by astroDimitrios** [astroDimitrios/rose#23]
![image](https://github.com/user-attachments/assets/21d507dc-cf32-4dcf-bf7f-ffca700d0122)

**Comment by astroDimitrios** [comment]
Example images of some graphs:

![image](https://github.com/user-attachments/assets/b0d4b37a-7a43-42d8-8499-b7122fa69d2c)

**Comment by astroDimitrios** [comment]
Graphing the metadata is currently blocked by the `DEAD_ENDS` in `rose.py`, removing the dead end results in the graphs appearing but we're not sure what the use case for the graphs are yet. The plotting is done by [pygraphviz](https://pygraphviz.github.io/documentation/stable/tutorial.html) in `metomi/rose/metadata_graph.py`, pygraphviz seems to be installed with the extras options when installing the env/Rose.

**Comment by J-J-Abram** [comment]
pygraphviz was blocked at vn1.8, but current version as of Sept 2024 is 1.14 - need to find out what the original issue at 1.8 was and if the later versions has solved it

**Comment by astroDimitrios** [comment]
Completed in [a24f04a](https://github.com/metomi/rose/commit/a24f04add19a5586d407ac907c1c9d39de1047f8)
