### ISSUE TITLE
Search box background text

### ISSUE THREAD

**Issue by astroDimitrios** [astroDimitrios/rose#24]
Add `Search` as placeholder text in the search entry box

**Comment by J-J-Abram** [comment]
Box is referred to as TOOLBAR_FIND = "Find expression (regex)" within init.py

Function for finding is within main.py line 1521:
def _launch_find(self, *args):
        """Get the find expression from a dialog."""

**Comment by astroDimitrios** [comment]
Enhancement added with [8df60a4](https://github.com/metomi/rose/commit/8df60a4306bbd54df181cb687bcce5473d2ce513).
