### ISSUE TITLE
rose edit errors on startup with `!` commented settings

### ISSUE THREAD

**Issue by jfrost-mo** [astroDimitrios/rose#28]
When I start rose edit, it errors with the following message, before exiting:

![Screenshot from 2024-09-20 00-54-53](https://github.com/user-attachments/assets/13d11973-af65-4c26-bef1-4fc20bd4927d)

It doesn't like the space character following the exclamation mark. If I have the setting against the exclamation mark there is no error.

This applies whether there is one or two exclamation marks.

**Comment by astroDimitrios** [comment]
@jfrost-mo Should there be a space in-between the exclamation mark and the variable? Is this a suite you have hand edited? Or was it originally saved/altered using the GUI?

**Comment by astroDimitrios** [comment]
I have just checked with `rose config-dump` and rose raises a `ConfigSyntaxError` when there is a space after the single or double exclamation mark in both Rose 2019 and Rose 2. Closing as not a GUI related issue.
