### ISSUE TITLE
Text boxes have orange background

### ISSUE THREAD

**Issue by jfrost-mo** [astroDimitrios/rose#29]
Tested on Met Office VDI.

![Screenshot from 2024-09-20 01-01-19](https://github.com/user-attachments/assets/0750ed8d-553d-4dc3-bd90-14ab4f04b798)

**Comment by jfrost-mo** [comment]
For comparison, rose 2019 has a white background on its boxes:

![Screenshot from 2024-09-20 03-50-36](https://github.com/user-attachments/assets/1a37fc6c-d04d-4656-a517-e7d0524b9563)

**Comment by oliver-sanders** [comment]
It's not orange, it's coral!

**Comment by jfrost-mo** [comment]
The NIWA position (while at the pub) was that the colour is an improvement.

**Comment by oliver-sanders** [comment]
(The "Coral" is a development joke, will obvs be changed to the theme FG colour)

**Comment by jfrost-mo** [comment]
Testing on the most recent version, this is now "fixed", much to the detriment of those artistically inclined.

**Comment by J-J-Abram** [comment]
Yes, its an easy css style change, currently controlled within this file:

metomi/rose/etc/rose-config-edit/style.css
