### ISSUE TITLE
Typing in python list widget is really laggy

### ISSUE THREAD

**Issue by jfrost-mo** [astroDimitrios/rose#32]
This is an issue that afflicts the rose edit 2019 too, but typing in the text box of a python list widget is really laggy, and often misses typed characters.

I susspect this is because it is reparsing the python list on every keypress, where is should really wait until the focus leaves the text box to do that, or at least have some kind of debouncing timeout. Fixing this would also help lessen the impack of #31.

**Comment by oliver-sanders** [comment]
I suspect this is a Rose 2019 issue so not really one for the porting project. Should be relatively easy to jam in a debounce  (something along the lines of https://stackoverflow.com/a/78227581).

**Comment by jfrost-mo** [comment]
Yeah, its an existing issue. So much for my secret plan to get these bugs fixes :grin: I'll reopen in the main repository.

**Comment by jfrost-mo** [comment]
Duplicate of https://github.com/metomi/rose/issues/2091

**Comment by oliver-sanders** [comment]
Fair enough, we have resourcing for the porting, but not for more fundamental improvements, maybe unless there's time left over...
