### ISSUE TITLE
Insufficient distinction between neighbouring config options

### ISSUE THREAD

**Issue by jfrost-mo** [astroDimitrios/rose#33]
When you have config options next to each other in rose edit, there is no visual distinction between one and the next.

In the following example it is hard to tell where one radio button ends, and the next begins.

![Screenshot from 2024-09-20 02-56-30](https://github.com/user-attachments/assets/86c9abc1-a86d-4ccf-be14-e90de7f72be6)

**Comment by jfrost-mo** [comment]
As a point of comparison, rose 2019 has a dividing line between these separate config options.

![Screenshot from 2024-09-20 03-47-59](https://github.com/user-attachments/assets/dce25e5d-2abf-400e-92e3-5b97bb7dbf60)

**Comment by J-J-Abram** [comment]
Looks like we need a separator widget:

https://docs.gtk.org/gtk3/class.Separator.html

and these will be needed between the keywidgets and their respective valuewudgets and the next key/valuewidget

**Comment by J-J-Abram** [comment]
The current issue with adding a separator widget is knowing when and when not to make them visible to match the variable widgets.

An alternative is to assign lines using css styling, the issue here is that GtK.Table has become depreciated (but not removed as of gtk3) so there is css support for it. 

We are able to make a 'soft' distinction between the variables by increasing the vertical padding `ypadding` between them in variables.py file, lines 250-255:

```
            container.attach(self.contentwidget,
                             key_col + 1, key_col + 2,
                             row_index, row_index + 1,
                             xpadding=5, ypadding=5,
                             xoptions=Gtk.AttachOptions.EXPAND | Gtk.AttachOptions.FILL,
                             yoptions=self.yoptions)
```

**Comment by J-J-Abram** [comment]
Issue potentially solved by removing any vertical padding that was added from previous comment and adding the following to the css styling:

metomi/rose/etc/rose-config-edit/style.css

```
notebook box > paned > paned > scrolledwindow > viewport > box > widget > box{ 
  border-bottom: solid;
  border-width: 1px;
  border-color: lightgray;
  padding: .4em;
  margin: 0 -.3em;
}
```

example:

<img width="947" alt="image" src="https://github.com/user-attachments/assets/92f74813-1110-4968-b9d9-7c83661d6673">
