### ISSUE TITLE
"Run suite" button is missing

### ISSUE THREAD

**Issue by jfrost-mo** [astroDimitrios/rose#38]
In the rose edit GUI in rose 2019 there is a "Run suite" play button in the header, that sets the workflow running (at least for cylc 7 workflows). This button is missing in the rose 2 version.

While I don't use it myself, as I instead directly use `cylc vip .`, talking to people at NIWA it is fairly frequently used here. Is it possible for the button to be reintroduced, ideally updated to handle cylc 8?

**Comment by oliver-sanders** [comment]
This button is gone and it ain't coming back!

Rose 2 is just a configuration editor.

Cylc is the workflow engine.

No more shall Rose attempt to control Cylc.
