### ISSUE TITLE
Page titles are not displaying

### ISSUE THREAD

**Issue by astroDimitrios** [astroDimitrios/rose#6]
See where it says `Page 0` should be `template variables` - there should also be a `x` symbol to close the page.

![image](https://github.com/user-attachments/assets/db764eee-cb3d-4a16-9717-422481f65687)

**Comment by J-J-Abram** [comment]
Possible location to look for solution
metomi/rose/config_editor
pagewidget - table.py
or
panelwidget

**Comment by astroDimitrios** [comment]
Closing as fixed.
